### ISSUE TITLE
ThematicBreak literal is lost in the Markdown renderer

### ISSUE THREAD

**Issue by jumale** [commonmark/commonmark-java#331]
Corresponding to [the specification](https://spec.commonmark.org/0.30/#thematic-breaks), thematic breaks can consist of 3 or more consecutive on of characters `-`, `_` or `*` with 0-3 leading spaces (i.e. regex `^\s{0,3}[-_*]{3,}$`).
This logic seem to be correct when reading Markdown - the thematic breaks are correctly recognised and captured as `ThematicBreak` node with `literal` parameter containing the actual value from the Markdown.
However, [during rendering](https://github.com/commonmark/commonmark-java/blob/114956af772cb82aa8f5c262e735aadcb0adc9cf/commonmark/src/main/java/org/commonmark/renderer/markdown/CoreMarkdownNodeRenderer.java#L93) the `literal` is dropped and replaced with static `___`

Expected behaviour: this markdown looks the same after parse/render
```md
foo

   *******

bar

---

baz
```

Actual behaviour: rendered transforms it into
```md
foo

___

bar

___

baz
```

**Comment by robinst** [comment]
Yeah. `MarkdownRenderer` does not yet preserve everything from the input, it's main focus is on producing an equivalent document (`___` is also a thematic break).

Would you want to try to make that change yourself and raise a PR? Looks like you've already found the right place where the fix should go :). I think in this case, if the node has a literal, we can use it, otherwise use `___` to not be ambiguous with lists.
