### ISSUE TITLE
[help wanted] Render contents of CustomNode

### ISSUE THREAD

**Issue by nicbotha** [commonmark/commonmark-java#345]
I've created a custom extension but I'm struggling to understand how to parse multi source line markdown in a CustomNode as HTML? Currently I'm using the InlineParser.parse(SourceLines var1, Node var2), which is working for basic markdown. 

As the **body** , see below, can potentially contain any markdown e.g. a table, I'm a bit lost on how to parse the source lines so that line spanning markdown will be detected and rendered? I don't want to have to re-create for example a table parser.

Can you please point me to what I'm missing?

**Markdown**:
!!! Heading
    **Body.**
    - **item** one
    - **item** two
    Body continue

**Expected result**:
`<ac:structured-macro>
	<ac:parameter ac:name="title">Heading</ac:parameter>
	<ac:rich-text-body>
		<p>
			<strong>Body.</strong>
			<ul>
				<li>
					<strong>item</strong> one</li>
				<li>
					<strong>item</strong> two</li>
			</ul>
		Body continue
		</p>
	</ac:rich-text-body>
</ac:structured-macro>`

**Actual result**. The list items are not parsed in this example and are still markdown.
`<ac:structured-macro><ac:parameter ac:name="title">Heading</ac:parameter><ac:rich-text-body><strong>Body<./strong>- <strong>item</strong> one - <strong>item</strong> two Body continue</ac:rich-text-body></ac:structured-macro>`

**Comment by Mian-Ahmed-Raza** [comment]
- It seems like you're currently using InlineParser.parse, which is typically used for inline elements and doesn't handle block elements (like lists, headings, or tables) properly. Instead, you might need a parser that can handle block elements.
- If you want to parse complete markdown blocks, you should look into using BlockParser or a similar parsing mechanism that can handle multi-line input and recognize different markdown structures.
- You can convert the body of your markdown into HTML and then wrap that in the desired XML structure. This ensures that nested markdown structures are parsed correctly.

Step 1: Create a Custom Block Parser
Instead of relying solely on the InlineParser, you should create a custom parser that can handle the overall structure of your markdown.
```
import { BlockParser } from 'your-markdown-library';

class CustomBlockParser extends BlockParser {
  parse(sourceLines, node) {
    // Your logic to identify the structure of the markdown
    const title = extractTitle(sourceLines); // Custom function to extract the title
    const bodyLines = extractBody(sourceLines); // Custom function to extract the body

    // Use a markdown parser to convert bodyLines to HTML
    const bodyHTML = convertMarkdownToHTML(bodyLines);

    // Construct the final structured macro output
    return `
      <ac:structured-macro>
        <ac:parameter ac:name="title">${title}</ac:parameter>
        <ac:rich-text-body>
          ${bodyHTML}
        </ac:rich-text-body>
      </ac:structured-macro>
    `;
  }
}

// Custom functions to handle specific parts of the markdown
function extractTitle(lines) {
  // Logic to extract the title from the first line
}

function extractBody(lines) {
  // Logic to extract body lines while preserving markdown structure
  return lines.slice(1); // Example: Skipping the first line for the title
}

function convertMarkdownToHTML(lines) {
  // Use a markdown library (like marked) to convert the lines into HTML
  return marked(lines.join('\n')); // Joining the lines and converting
}
```
Step 2: Register the Custom Block Parser
You need to ensure that your custom block parser is registered in the markdown parsing pipeline so that it can be invoked when processing the markdown content.
```
import { Parser } from 'your-markdown-library';

const parser = new Parser();
parser.registerBlockParser(new CustomBlockParser());
```
Step 3: Handle Line Spanning Markdown
To address the issue of line spanning markdown structures (like tables or lists), make sure your custom parser can handle the markdown's context:

- Keep track of which lines belong to the same block or structure.
- Ensure that you properly segment lists, headings, and paragraphs as you build the HTML output.

With this setup, your parser should be able to produce the expected output while correctly parsing more complex markdown structures:
```
<ac:structured-macro>
  <ac:parameter ac:name="title">Heading</ac:parameter>
  <ac:rich-text-body>
    <p><strong>Body.</strong></p>
    <ul>
      <li><strong>item</strong> one</li>
      <li><strong>item</strong> two</li>
    </ul>
    <p>Body continue</p>
  </ac:rich-text-body>
</ac:structured-macro>
```

**Comment by nicbotha** [comment]
I've tried your recommendation and it works. Thank you very much. Closing this issue.
